export type AssetRecord = {
  id: number;
  assetRegistrationNo: string;
  assetName: string;
  usageDescription: string;
  assetGroup: "Hardware" | "Software";
  deviceType: string;
  operatingSystem: string;
  privateIp: string;
  publicIp?: string;
  locationDetail: string;
  currentStatus: "Active" | "Inactive" | "Broken";
  ownerName: string;
  updatedBy: string;
  updatedAt: string;
  maintenanceEndDate: string;
  manufacturerBrand: string;
  serialNumber: string;
};

export type FacilitySurvey = {
  facilityId: number;
  facilityName: string;
  districtName: string;
  surveyDate: string;
  personnelCount: number;
  completionRate: number;
  lastUpdatedBy: string;
  assets: AssetRecord[];
};

export const facilitySurveys: FacilitySurvey[] = [
  // ── สสจ.สตูล (facility_id=65) ─────────────────────────────────────
  {
    facilityId: 65,
    facilityName: "สสจ.สตูล",
    districtName: "เมืองสตูล",
    surveyDate: "2026-05-04",
    personnelCount: 92,
    completionRate: 96,
    lastUpdatedBy: "Sa Admin",
    assets: [
      {
        id: 1,
        assetRegistrationNo: "SAT-MOPH-HW-0001",
        assetName: "Core Firewall",
        usageDescription: "ควบคุมการเข้าออกเครือข่ายส่วนกลางของจังหวัด",
        assetGroup: "Hardware",
        deviceType: "Firewall",
        operatingSystem: "FortiOS 7.4",
        privateIp: "10.10.0.1",
        publicIp: "203.113.10.5",
        locationDetail: "Data Corner ชั้น 2 อาคารอำนวยการ",
        currentStatus: "Active",
        ownerName: "นายอิรฟาน หลงเด็น",
        updatedBy: "Sa Admin",
        updatedAt: "2026-05-06 09:20",
        maintenanceEndDate: "2026-05-28",
        manufacturerBrand: "Fortinet",
        serialNumber: "FGT90G-SATUL-01",
      },
      {
        id: 2,
        assetRegistrationNo: "SAT-MOPH-SYS-0002",
        assetName: "VM Host A",
        usageDescription: "รัน HIS, dashboard และระบบรายงานภายใน",
        assetGroup: "Software",
        deviceType: "Linux",
        operatingSystem: "Ubuntu Server 24.04",
        privateIp: "10.10.0.20",
        locationDetail: "Server Rack A1",
        currentStatus: "Active",
        ownerName: "นางสาวสุชาดา ทองมาก",
        updatedBy: "NOC Satun",
        updatedAt: "2026-05-05 14:05",
        maintenanceEndDate: "2026-10-15",
        manufacturerBrand: "Dell",
        serialNumber: "DL-SATUL-A1",
      },
      {
        id: 7,
        assetRegistrationNo: "SAT-MOPH-NW-0003",
        assetName: "Core Switch L3",
        usageDescription: "กระจายสัญญาณหลักระหว่าง VLAN ภายในสสจ.",
        assetGroup: "Hardware",
        deviceType: "Switch",
        operatingSystem: "ArubaOS 10.x",
        privateIp: "10.10.0.2",
        locationDetail: "Data Corner ชั้น 2 อาคารอำนวยการ",
        currentStatus: "Active",
        ownerName: "นายอิรฟาน หลงเด็น",
        updatedBy: "Sa Admin",
        updatedAt: "2026-05-06 09:25",
        maintenanceEndDate: "2026-12-31",
        manufacturerBrand: "HP Aruba",
        serialNumber: "ARB-5400-MOPH-01",
      },
      {
        id: 8,
        assetRegistrationNo: "SAT-MOPH-HW-0004",
        assetName: "UPS ระบบกลาง",
        usageDescription: "สำรองไฟสำหรับห้อง Server และ Network ชั้น 2",
        assetGroup: "Hardware",
        deviceType: "UPS",
        operatingSystem: "Firmware (APC)",
        privateIp: "-",
        locationDetail: "ห้อง Server ชั้น 2 อาคารอำนวยการ",
        currentStatus: "Active",
        ownerName: "นางสาวสุชาดา ทองมาก",
        updatedBy: "Sa Admin",
        updatedAt: "2026-05-04 10:00",
        maintenanceEndDate: "2027-03-15",
        manufacturerBrand: "APC",
        serialNumber: "APC-SMART5K-MOPH-01",
      },
    ],
  },

  // ── รพ.สตูล (facility_id=1) ────────────────────────────────────────
  {
    facilityId: 1,
    facilityName: "รพ.สตูล",
    districtName: "เมืองสตูล",
    surveyDate: "2026-05-03",
    personnelCount: 214,
    completionRate: 88,
    lastUpdatedBy: "ศูนย์ IT รพ.สตูล",
    assets: [
      {
        id: 3,
        assetRegistrationNo: "SAT-HOS-HW-0108",
        assetName: "X-Ray Review Workstation",
        usageDescription: "เครื่องอ่านผลภาพถ่ายรังสี",
        assetGroup: "Hardware",
        deviceType: "Windows",
        operatingSystem: "Windows 11 Pro",
        privateIp: "172.16.8.21",
        locationDetail: "ห้อง X-Ray OPD",
        currentStatus: "Active",
        ownerName: "นายธีรพงศ์ ชูช่วย",
        updatedBy: "ศูนย์ IT รพ.สตูล",
        updatedAt: "2026-05-04 11:40",
        maintenanceEndDate: "2026-06-11",
        manufacturerBrand: "HP",
        serialNumber: "HPXR-8841",
      },
      {
        id: 4,
        assetRegistrationNo: "SAT-HOS-NW-0114",
        assetName: "Radiology Switch",
        usageDescription: "กระจายสัญญาณห้องรังสีและ PACS",
        assetGroup: "Hardware",
        deviceType: "Switch",
        operatingSystem: "Embedded OS",
        privateIp: "172.16.8.2",
        locationDetail: "Rack R2 ห้องรังสี",
        currentStatus: "Broken",
        ownerName: "นายธีรพงศ์ ชูช่วย",
        updatedBy: "Field Audit 2",
        updatedAt: "2026-05-03 16:22",
        maintenanceEndDate: "2026-05-19",
        manufacturerBrand: "Cisco",
        serialNumber: "CSW-RD-0114",
      },
      {
        id: 9,
        assetRegistrationNo: "SAT-HOS-SYS-0115",
        assetName: "HIS Application Server",
        usageDescription: "ให้บริการระบบ HIS สำหรับแผนกทั้งหมดของโรงพยาบาล",
        assetGroup: "Software",
        deviceType: "Linux",
        operatingSystem: "CentOS 7",
        privateIp: "172.16.1.10",
        locationDetail: "Server Rack หลัก ห้องสื่อสาร",
        currentStatus: "Active",
        ownerName: "นายธีรพงศ์ ชูช่วย",
        updatedBy: "ศูนย์ IT รพ.สตูล",
        updatedAt: "2026-05-03 12:00",
        maintenanceEndDate: "2026-08-30",
        manufacturerBrand: "Dell",
        serialNumber: "DL-HIS-SRV-HOSP-01",
      },
      {
        id: 10,
        assetRegistrationNo: "SAT-HOS-NW-0116",
        assetName: "Internet Edge Router",
        usageDescription: "เชื่อมต่ออินเทอร์เน็ตหลักของโรงพยาบาล",
        assetGroup: "Hardware",
        deviceType: "Router",
        operatingSystem: "RouterOS v7",
        privateIp: "172.16.0.1",
        publicIp: "49.228.110.20",
        locationDetail: "ห้องสื่อสาร ชั้น 1 อาคาร OPD",
        currentStatus: "Active",
        ownerName: "นายธีรพงศ์ ชูช่วย",
        updatedBy: "ศูนย์ IT รพ.สตูล",
        updatedAt: "2026-05-03 12:10",
        maintenanceEndDate: "2026-11-20",
        manufacturerBrand: "MikroTik",
        serialNumber: "MTK-RB1100-HOSP-01",
      },
    ],
  },

  // ── รพ.ละงู (facility_id=7) ────────────────────────────────────────
  {
    facilityId: 7,
    facilityName: "รพ.ละงู",
    districtName: "ละงู",
    surveyDate: "2026-05-02",
    personnelCount: 61,
    completionRate: 74,
    lastUpdatedBy: "ทีมสำรวจละงู",
    assets: [
      {
        id: 5,
        assetRegistrationNo: "SAT-LNG-ST-0203",
        assetName: "NAS Backup Unit",
        usageDescription: "เก็บข้อมูลสำรองระบบห้องคลอดและการเงิน",
        assetGroup: "Hardware",
        deviceType: "NAS",
        operatingSystem: "Synology DSM 7.2",
        privateIp: "10.20.4.10",
        locationDetail: "ห้องแม่ข่าย ชั้น 1",
        currentStatus: "Inactive",
        ownerName: "นางสาวอาซียะห์ ดอเลาะ",
        updatedBy: "ทีมสำรวจละงู",
        updatedAt: "2026-05-02 13:18",
        maintenanceEndDate: "2026-05-22",
        manufacturerBrand: "Synology",
        serialNumber: "SYN-0203-LNG",
      },
      {
        id: 6,
        assetRegistrationNo: "SAT-LNG-SYS-0204",
        assetName: "AD Domain Controller",
        usageDescription: "จัดการสิทธิ์ผู้ใช้งานในเครือข่ายโรงพยาบาล",
        assetGroup: "Software",
        deviceType: "Windows",
        operatingSystem: "Windows Server 2022",
        privateIp: "10.20.4.12",
        publicIp: "1.20.130.44",
        locationDetail: "Server Rack B2",
        currentStatus: "Active",
        ownerName: "นายวสันต์ นวลแก้ว",
        updatedBy: "NOC Satun",
        updatedAt: "2026-05-07 10:02",
        maintenanceEndDate: "2026-07-30",
        manufacturerBrand: "Lenovo",
        serialNumber: "LNV-0204-DC",
      },
      {
        id: 11,
        assetRegistrationNo: "SAT-LNG-HW-0205",
        assetName: "Network Laser Printer",
        usageDescription: "พิมพ์เอกสารทั่วไปและใบเสร็จรับเงินสำหรับแผนกเวชระเบียน",
        assetGroup: "Hardware",
        deviceType: "Printer",
        operatingSystem: "Embedded OS",
        privateIp: "10.20.4.50",
        locationDetail: "ห้องเวชระเบียน ชั้น 1",
        currentStatus: "Active",
        ownerName: "นายวสันต์ นวลแก้ว",
        updatedBy: "ทีมสำรวจละงู",
        updatedAt: "2026-05-02 14:00",
        maintenanceEndDate: "2027-01-10",
        manufacturerBrand: "HP",
        serialNumber: "HPP-LJP4015-LNG-01",
      },
    ],
  },

  // ── รพ.ควนกาหลง (facility_id=2) ───────────────────────────────────
  {
    facilityId: 2,
    facilityName: "รพ.ควนกาหลง",
    districtName: "ควนกาหลง",
    surveyDate: "2026-05-01",
    personnelCount: 78,
    completionRate: 82,
    lastUpdatedBy: "ทีมสำรวจควนกาหลง",
    assets: [
      {
        id: 12,
        assetRegistrationNo: "SAT-KLG-HW-0301",
        assetName: "Firewall UTM",
        usageDescription: "ป้องกันเครือข่ายและกรองทราฟฟิคขาเข้า-ขาออกของโรงพยาบาล",
        assetGroup: "Hardware",
        deviceType: "Firewall",
        operatingSystem: "FortiOS 7.4",
        privateIp: "192.168.1.1",
        publicIp: "1.1.228.35",
        locationDetail: "Data Room ชั้น 1 อาคารอำนวยการ",
        currentStatus: "Active",
        ownerName: "นายกมล แซ่โค้ว",
        updatedBy: "ทีมสำรวจควนกาหลง",
        updatedAt: "2026-05-01 10:30",
        maintenanceEndDate: "2026-09-15",
        manufacturerBrand: "Fortinet",
        serialNumber: "FGT60F-KLG-01",
      },
      {
        id: 13,
        assetRegistrationNo: "SAT-KLG-NW-0302",
        assetName: "Core Switch",
        usageDescription: "กระจายสัญญาณหลักระหว่างแผนกต่าง ๆ ภายในโรงพยาบาล",
        assetGroup: "Hardware",
        deviceType: "Switch",
        operatingSystem: "Embedded OS",
        privateIp: "192.168.1.2",
        locationDetail: "Data Room ชั้น 1 อาคารอำนวยการ",
        currentStatus: "Active",
        ownerName: "นายกมล แซ่โค้ว",
        updatedBy: "ทีมสำรวจควนกาหลง",
        updatedAt: "2026-05-01 10:45",
        maintenanceEndDate: "2026-06-05",
        manufacturerBrand: "Cisco",
        serialNumber: "CSW-KLG-C2960-01",
      },
      {
        id: 14,
        assetRegistrationNo: "SAT-KLG-HW-0303",
        assetName: "OPD Workstation",
        usageDescription: "ใช้บันทึกข้อมูลผู้ป่วยนอกและออกใบสั่งยา",
        assetGroup: "Hardware",
        deviceType: "Windows",
        operatingSystem: "Windows 10 Pro",
        privateIp: "192.168.2.44",
        locationDetail: "ห้อง OPD ชั้น 1",
        currentStatus: "Broken",
        ownerName: "นางสาวมาเรียม สาเรง",
        updatedBy: "ทีมสำรวจควนกาหลง",
        updatedAt: "2026-05-01 11:00",
        maintenanceEndDate: "2025-12-31",
        manufacturerBrand: "Lenovo",
        serialNumber: "LNV-OPD-KLG-0303",
      },
    ],
  },

  // ── รพ.ทุ่งหว้า (facility_id=5) ───────────────────────────────────
  {
    facilityId: 5,
    facilityName: "รพ.ทุ่งหว้า",
    districtName: "ทุ่งหว้า",
    surveyDate: "2026-04-28",
    personnelCount: 55,
    completionRate: 71,
    lastUpdatedBy: "ทีมสำรวจทุ่งหว้า",
    assets: [
      {
        id: 15,
        assetRegistrationNo: "SAT-THW-NW-0401",
        assetName: "Internet Router",
        usageDescription: "เชื่อมต่ออินเทอร์เน็ตผ่าน ISP และทำ NAT สำหรับเครือข่ายภายใน",
        assetGroup: "Hardware",
        deviceType: "Router",
        operatingSystem: "RouterOS v7",
        privateIp: "10.30.0.1",
        publicIp: "49.49.214.8",
        locationDetail: "ห้องสื่อสาร ชั้น 1",
        currentStatus: "Active",
        ownerName: "นายสมชาย หาดทิพย์",
        updatedBy: "ทีมสำรวจทุ่งหว้า",
        updatedAt: "2026-04-28 09:00",
        maintenanceEndDate: "2026-07-20",
        manufacturerBrand: "MikroTik",
        serialNumber: "MTK-CCR1009-THW-01",
      },
      {
        id: 16,
        assetRegistrationNo: "SAT-THW-ST-0402",
        assetName: "NAS Backup",
        usageDescription: "สำรองข้อมูล EMR และภาพถ่ายทางการแพทย์ทุกคืน",
        assetGroup: "Hardware",
        deviceType: "NAS",
        operatingSystem: "Synology DSM 7.2",
        privateIp: "10.30.0.20",
        locationDetail: "ห้อง Server ชั้น 2",
        currentStatus: "Inactive",
        ownerName: "นายสมชาย หาดทิพย์",
        updatedBy: "ทีมสำรวจทุ่งหว้า",
        updatedAt: "2026-04-28 09:20",
        maintenanceEndDate: "2026-05-15",
        manufacturerBrand: "Synology",
        serialNumber: "SYN-DS923-THW-01",
      },
      {
        id: 17,
        assetRegistrationNo: "SAT-THW-SYS-0403",
        assetName: "Antivirus Management Server",
        usageDescription: "บริหารจัดการ endpoint protection สำหรับเครื่องในโรงพยาบาลทั้งหมด",
        assetGroup: "Software",
        deviceType: "Windows",
        operatingSystem: "Windows Server 2019",
        privateIp: "10.30.0.30",
        locationDetail: "Server Rack ห้อง Server ชั้น 2",
        currentStatus: "Active",
        ownerName: "นายสมชาย หาดทิพย์",
        updatedBy: "ทีมสำรวจทุ่งหว้า",
        updatedAt: "2026-04-28 09:40",
        maintenanceEndDate: "2026-10-01",
        manufacturerBrand: "Dell",
        serialNumber: "DL-PE340-AV-THW-01",
      },
    ],
  },

  // ── รพ.มะนัง (facility_id=6) ───────────────────────────────────────
  {
    facilityId: 6,
    facilityName: "รพ.มะนัง",
    districtName: "มะนัง",
    surveyDate: "2026-04-30",
    personnelCount: 43,
    completionRate: 79,
    lastUpdatedBy: "ทีมสำรวจมะนัง",
    assets: [
      {
        id: 18,
        assetRegistrationNo: "SAT-MNG-NW-0501",
        assetName: "Access Point Controller",
        usageDescription: "ควบคุมและกระจายสัญญาณ Wi-Fi ภายในอาคารรักษาพยาบาลทั้งหมด",
        assetGroup: "Hardware",
        deviceType: "Access Point",
        operatingSystem: "UniFi Network OS",
        privateIp: "10.40.0.10",
        locationDetail: "ชั้น 1 อาคารรักษาพยาบาล",
        currentStatus: "Active",
        ownerName: "นายรุสดี สาและ",
        updatedBy: "ทีมสำรวจมะนัง",
        updatedAt: "2026-04-30 10:00",
        maintenanceEndDate: "2026-08-20",
        manufacturerBrand: "Ubiquiti",
        serialNumber: "UAP-PRO-MNG-01",
      },
      {
        id: 19,
        assetRegistrationNo: "SAT-MNG-SYS-0502",
        assetName: "Patient DB Server",
        usageDescription: "ฐานข้อมูลผู้ป่วยและประวัติการรักษาของโรงพยาบาลมะนัง",
        assetGroup: "Software",
        deviceType: "Linux",
        operatingSystem: "Ubuntu Server 22.04 LTS",
        privateIp: "10.40.0.20",
        locationDetail: "ห้อง Server ชั้น 1",
        currentStatus: "Active",
        ownerName: "นายรุสดี สาและ",
        updatedBy: "ทีมสำรวจมะนัง",
        updatedAt: "2026-04-30 10:20",
        maintenanceEndDate: "2026-12-25",
        manufacturerBrand: "HP",
        serialNumber: "HPE-ML30-MNG-01",
      },
      {
        id: 20,
        assetRegistrationNo: "SAT-MNG-HW-0503",
        assetName: "OPD Workstation 1",
        usageDescription: "ใช้บันทึกข้อมูลผู้ป่วยนอกแผนกอายุรกรรม",
        assetGroup: "Hardware",
        deviceType: "Windows",
        operatingSystem: "Windows 11 Pro",
        privateIp: "10.40.2.11",
        locationDetail: "ห้อง OPD แผนกอายุรกรรม",
        currentStatus: "Broken",
        ownerName: "นางสาวนิสา มาหะมะ",
        updatedBy: "ทีมสำรวจมะนัง",
        updatedAt: "2026-04-30 11:00",
        maintenanceEndDate: "2026-05-25",
        manufacturerBrand: "Lenovo",
        serialNumber: "LNV-OPD-MNG-0503",
      },
    ],
  },
];

export const districtCoverage = [
  { district: "เมืองสตูล", completionRate: 91, facilities: 2, x: "16%", y: "28%" },
  { district: "ควนโดน", completionRate: 68, facilities: 4, x: "56%", y: "18%" },
  { district: "ควนกาหลง", completionRate: 73, facilities: 4, x: "47%", y: "40%" },
  { district: "ท่าแพ", completionRate: 62, facilities: 3, x: "60%", y: "58%" },
  { district: "ละงู", completionRate: 74, facilities: 5, x: "20%", y: "64%" },
  { district: "ทุ่งหว้า", completionRate: 59, facilities: 4, x: "12%", y: "82%" },
  { district: "มะนัง", completionRate: 66, facilities: 3, x: "76%", y: "72%" },
];